language: c
dist: precise
env:
  global:
    - PAGER=cat
    - HIVE_HOME=/opt/apache-hive-2.1.1-bin
    - HADOOP_HOME=/opt/hadoop-2.7.2

before_install:
  # Decrypt config files
  - openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/hive.config.enc -out $TRAVIS_BUILD_DIR/test/config/hive.config -d
  - openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/postgres.config.enc -out $TRAVIS_BUILD_DIR/test/config/postgres.config -d
  - openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/mysql.config.enc -out $TRAVIS_BUILD_DIR/test/config/mysql.config -d
  - openssl aes-256-cbc -K $encrypted_d52b986e6313_key -iv $encrypted_d52b986e6313_iv -in $TRAVIS_BUILD_DIR/test/config/sqlserver.config.enc -out $TRAVIS_BUILD_DIR/test/config/sqlserver.config -d

  # Add custom PPAs from cartodb
  - sudo add-apt-repository -y ppa:cartodb/postgresql-9.5
  - sudo add-apt-repository -y ppa:cartodb/odbc
  # Add PostgreSQL 9.6. Due to we use precise right now, we don't have an odbc for trusty 
  - sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update

  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo rm -rf /var/lib/postgresql/
  - sudo rm -rf /var/log/postgresql/
  - sudo rm -rf /etc/postgresql/
  - sudo apt-get -y remove --purge postgis-2.2
  - sudo apt-get -y autoremove

install:
  - sudo bash ./test/scripts/ci/install_dependencies.sh

  # Add localhost to known hosts file for SSH connection which is done by HADOOP in its initialization
  - echo -e "Host *\n   StrictHostKeyChecking no" | sudo tee ~/.ssh/config
  - ssh-keygen -t dsa -P '' -f ~/.ssh/id_dsa
  - cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
  - chmod 0600 ~/.ssh/authorized_keys

before_script:
  # Start of hadoop and hive services
  - $HADOOP_HOME/sbin/start-dfs.sh
  - $HIVE_HOME/bin/schematool -initSchema -dbType derby
  - nohup $HIVE_HOME/bin/hive --service hiveserver2 &
  # Wait 10 seconds for HIVE server to start
  - sleep 10

  - sudo bash ./test/scripts/ci/load_fixtures.sh

script:
  - sudo bash ./test/scripts/ci/integration_tests.sh
